export const COMPLETED_WALLET_SETUP = 'COMPLETED_WALLET_SETUP';
export const WALLET_SETUP_FAILED = 'WALLET_SETUP_FAILED';
export const SETUP_WALLET = 'SETUP_WALLET';
export const VERIFY_WALLET = 'VERIFY_WALLET';
export const INCORRECT_PASSCODE = 'INCORRECT_PASSCODE';
export const SUCCESSFULL_LOGIN = 'SUCCESSFULL_LOGIN';
export const LOGIN_REFRESH = 'LOGIN_REFRESH';
